<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="DataSets\dsCustomersRegistration.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsCustomersRegistration.xsd</DependentUpon>
    </Compile>
    <Compile Update="DataSets\dsPopularBooks.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>dsPopularBooks.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataSets\dsCustomersRegistration.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsCustomersRegistration.Designer.cs</LastGenOutput>
    </None>
    <None Update="DataSets\dsPopularBooks.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>dsPopularBooks.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>