<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="nlog.config" />
    <Content Remove="wwwroot\Reports\rptCustomerRegistration.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="nlog.config" />
    <_ContentIncludedByDefault Remove="wwwroot\css\forms.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="nlog.config" />
    <None Include="wwwroot\Reports\rptCustomerRegistration.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCoreHero.ToastNotification" Version="1.1.0" />
    <PackageReference Include="EPPlus" Version="7.2.2" />
    <PackageReference Include="itext7" Version="8.0.4" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.4" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Localization" Version="2.2.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0-3.final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="ReportViewerCore.NETCore" Version="15.1.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Library.Data\Library.Data.csproj" />
    <ProjectReference Include="..\Library.Service\Library.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ReportDataSet\dsCustomersRegistration.Designer.cs">
      <DependentUpon>dsCustomersRegistration.xsd</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="ReportDataSet\dsCustomersRegistration.xsd">
      <SubType>Designer</SubType>
      <LastGenOutput>dsCustomersRegistration.Designer.cs</LastGenOutput>
      <Generator>MSDataSetGenerator</Generator>
    </None>
  </ItemGroup>

</Project>
